# ==================================================
# General parameters
# ==================================================

# NAME of this run
name: "exp99-generate-embeddings"
seed: 42

# dataset
dataset: "iclevr"
dataset_path: "./data/iCLEVR/clevr_train.h5"
valid_dataset_path: "./data/iCLEVR/clevr_val.h5"
test_dataset_path: "./data/iCLEVR/clevr_test.h5"
glove_path: "./data/misc/glove_codraw_iclevr.txt"

# negative samples
negative_samples: true
negative_N: 1
substitute_rate: 0.25

# run
batch_size: 50
num_workers: 2

# ==================================================
# Special parameters
# ==================================================

fork: "exp95"
model_path: "./results/experiments/exp95-pretrain-tirg/snapshots/iclevr_pretrain_models_epoch_34.pth"

sentence_encoder_type: "bert"
text_dim: 768

save_root_dir: "./data/iCLEVR/"