# ==================================================
# General parameters
# ==================================================

# NAME of this run
name: "exp102-3-generate-embeddings"
seed: 42

# dataset
dataset: "iclevr-round"
dataset_path: "./data/iCLEVR-round/clevr_train.h5"
valid_dataset_path: "./data/iCLEVR-round/clevr_val.h5"
test_dataset_path: "./data/iCLEVR-round/clevr_test.h5"
glove_path: "./data/misc/glove_codraw_iclevr.txt"

# rel_enhance
rel_enhance: true

# run
batch_size: 50
num_workers: 2

# ==================================================
# Special parameters
# ==================================================

fork: "exp97"
model_path: "./results/experiments/exp97-pretrain-tirg/snapshots/iclevr-round_pretrain_models_epoch_13.pth"

sentence_encoder_type: "bert"
text_dim: 768

save_root_dir: "./data/iCLEVR-round/"